version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false  # כיבוי האימות
    ports:
      - "9201:9200"  # גישה ל-Elasticsearch
    networks:
      - elastic_network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data  # לשמור את הנתונים על דיסק

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # קישור ל-Elasticsearch
      - xpack.security.enabled=false  # כיבוי האימות גם כאן
    ports:
      - "5601:5601"  # גישה ל-Kibana
    networks:
      - elastic_network
    depends_on:
      - elasticsearch

networks:
  elastic_network:
    driver: bridge

volumes:
  elasticsearch_data:
