version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # יצא את הפורט 9090 שזו ה-interface של Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"  # יצא את הפורט 3000 שזו ה-interface של Grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # סיסמה למנהל
    depends_on:
      - prometheus
    restart: always
