name: Infrastructures Deployment

on:
  push:
    #paths:
    #  - 'my-server/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Docker Login
        run: |
          username="shacharavraham"
          username="shacharavraham"
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u $username --password-stdin

      - name: Build
        run: |
          cd my-server
          docker build -t orderappserver .
          docker tag orderappserver shacharavraham/orderappserver:latest

      - name: Push
        run: |
          docker push shacharavraham/orderappserver:latest